site_name: wiki of peiyuzou
site_description: peiyuzou's knowledge wiki
site_url: https://peiyuzou.github.io/
# repo_url: https://github.com/PeiyuZou/PeiyuZou.github.io 展示github仓库信息
# repo_name: peiyuzou/peiyuzou.github.op
theme:
  name: material
  logo: blog/images/peiyuzou.png # 界面内的Logo
  favicon: blog/images/peiyuzou.png # 浏览器页签的Logo
  features:
    - navigation.instant # 页面无刷新切换
    - navigation.instant.progress # 页面切换进度条
    - navigation.tracking # 滚动时URL锚点自动更新
    - navigation.tabs # 一级导航显示为顶部Tab
    - navigation.tabs.sticky # 滚动时不隐藏顶部Tab
    # - navigation.sections # 侧边导航不折叠而是分组
    - navigation.expand # 侧边导航默认展开所有目录
    - navigation.path # 文章上方面包屑导航
    - navigation.prune # 优化选项-导航修剪（网站物理大小减少33%以上）
    - navigation.indexes # 章节折叠页可阅读（让折叠节点支持阅读，具体指向在下方的nav中配置）
    - toc.follow # 目录跟随滚动
    # - toc.integrate # 目录集成到侧边导航（显示上太臃肿了不建议）
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索共享
    - navigation.footer # 页脚（上下页）
    - content.code.copy # 允许代码块复制
    - content.code.select # 允许代码块选择
    - content.code.annotate # 代码注释
    - content.footnote.tooltips # 脚注
    - content.tooltips # 工具提示
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: black # 主色
      accent: indigo # 强调色
      toggle:
        icon: material/lightbulb
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: 切换至日间模式
  # font:
  #   text: Roboto
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github #右上角图标
    previous: fontawesome/solid/angle-left
    # top: fontawesome/solid/angles-up
    alternate: fontawesome/solid/language

copyright: Copyright &copy; 2023 - 2025 peiyuzou

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      # categories_allowed:
      #     - Holidays
      #     - News
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      # post_slugify: !!python/object/apply:ext.slugs.slugify
      #   kwds:
      #     short: true
  - meta
  - tags:
      tags_file: blog/tags.md
  - glightbox # 图片插件

nav:
  - 首页: index.md
  - 计算机科学:
    - CrashCourse:
      - 01.算数逻辑单元: 01_计算机科学/CrashCourse/01_算数逻辑单元.md
      - 02.寄存器和内存: 01_计算机科学/CrashCourse/02_寄存器和内存.md
      - 03.中央处理器: 01_计算机科学/CrashCourse/03_中央处理器.md
      - 04.高级CPU设计: 01_计算机科学/CrashCourse/04_高级CPU设计.md
    - 操作系统:
      - 00.前言:
        - 0.1 前言: 01_计算机科学/操作系统/00_前言/0_1_前言.md
      - 01.硬件结构:
        - 1.1 冯诺依曼模型: 01_计算机科学/操作系统/01_硬件结构/1_1_冯诺依曼模型.md
        - 1.2 存储设备: 01_计算机科学/操作系统/01_硬件结构/1_2_存储设备.md
        - 1.3 CPU Cache: 01_计算机科学/操作系统/01_硬件结构/1_3_CPU_Cache.md
    - 数据结构与算法:
      - 01.概览:
        - 1.1 数据结构与算法概览: 01_计算机科学/数据结构和算法/01_概览/1_1_数据结构和算法概览.md
      - 02.复杂度分析:
        - 2.1 算法效率评估: 01_计算机科学/数据结构和算法/02_复杂度分析/2_1_算法效率评估.md
        - 2.2 迭代和递归: 01_计算机科学/数据结构和算法/02_复杂度分析/2_2_迭代和递归.md
        - 2.3 时间复杂度: 01_计算机科学/数据结构和算法/02_复杂度分析/2_3_时间复杂度.md
        - 2.4 空间复杂度: 01_计算机科学/数据结构和算法/02_复杂度分析/2_4_空间复杂度.md
      - 03.数据结构:
        - 3.1 数据结构的分类: 01_计算机科学/数据结构和算法/03_数据结构/3_1_数据结构的分类.md
        - 3.2 基本数据类型: 01_计算机科学/数据结构和算法/03_数据结构/3_2_基本数据类型.md
        - 3.3 数字编码: 01_计算机科学/数据结构和算法/03_数据结构/3_3_数字编码.md
      - 04.数组与链表:
        - 4.1 数组: 01_计算机科学/数据结构和算法/04_数组与链表/4_1_数组.md
        - 4.2 链表: 01_计算机科学/数据结构和算法/04_数组与链表/4_2_链表.md
        - 4.3 列表: 01_计算机科学/数据结构和算法/04_数组与链表/4_3_列表.md
        - 4.4 内存与缓存: 01_计算机科学/数据结构和算法/04_数组与链表/4_4_内存与缓存.md
        - 4.5 相关问题: 01_计算机科学/数据结构和算法/04_数组与链表/4_5_相关问题.md
      - 05.栈与队列:
        - 5.1 栈: 01_计算机科学/数据结构和算法/05_栈与队列/5_1_栈.md
        - 5.2 队列: 01_计算机科学/数据结构和算法/05_栈与队列/5_2_队列.md
        - 5.3 双向队列: 01_计算机科学/数据结构和算法/05_栈与队列/5_3_双向队列.md
        - 5.4 相关问题: 01_计算机科学/数据结构和算法/05_栈与队列/5_4_相关问题.md
      - 06.哈希表:
        - 6.1 哈希表: 01_计算机科学/数据结构和算法/06_哈希表/6_1_哈希表.md
        - 6.2 哈希冲突: 01_计算机科学/数据结构和算法/06_哈希表/6_2_哈希冲突.md
        - 6.3 哈希算法: 01_计算机科学/数据结构和算法/06_哈希表/6_3_哈希算法.md
  - 编程语言:
    - C#:
      - 匿名函数和闭包问题: 02_编程语言/CSharp/匿名函数和闭包问题.md
      - List源码浅析: 02_编程语言/CSharp/List源码浅析.md
    - Lua:
      - Lua基础:
        - 01.Lua数值: 02_编程语言/Lua/Lua基础/01_Lua数值.md
        - 02.Lua字符串: 02_编程语言/Lua/Lua基础/02_Lua字符串.md
        - 03.Lua函数: 02_编程语言/Lua/Lua基础/03_Lua函数.md
      - 源码阅读:
        - 00.概览:
          - 0.1 概览: 02_编程语言/Lua/源码阅读/00_概览/0_1_概览.md
        - 01.全局状态机及内存:
          - 1.1 全局状态机及内存管理: 02_编程语言/Lua/源码阅读/01_全局状态机及内存/1_1_全局状态机及内存管理.md
        - 02.数据类型:
          - 2.1 Lua中的数据类型: 02_编程语言/Lua/源码阅读/02_数据类型/2_1_Lua中的数据类型.md
        - 03.字符串:
          - 3.1 字符串的数据结构设计: 02_编程语言/Lua/源码阅读/03_字符串/3_1_字符串的数据结构设计.md
          - 3.2 字符串的相关实现: 02_编程语言/Lua/源码阅读/03_字符串/3_2_字符串的相关实现.md
        - 04.表:
          - 4.1 表的数据结构: 02_编程语言/Lua/源码阅读/04_表/4_1_表的数据结构.md
          - 4.2 表相关的算法: 02_编程语言/Lua/源码阅读/04_表/4_2_表相关的算法.md
        - 05.虚拟机:
          - 5.1 Lua执行的大致过程: 02_编程语言/Lua/源码阅读/05_虚拟机/5_1_Lua执行的大致过程.md
          - 5.x 虚拟机相关函数解读: 02_编程语言/Lua/源码阅读/05_虚拟机/5_x_虚拟机相关函数解读.md
  - 游戏编程:
    - 压缩算法:
      - 01.Lz4: 03_游戏编程/压缩算法/01_Lz4.md
  - 性能优化:
    - Unity内存管理:
      - 01.什么是内存: 04_性能优化/Unity内存管理/01_什么是内存.md
      - 02.Android内存管理: 04_性能优化/Unity内存管理/02_Android内存管理.md
      - 03.Unity内存简介: 04_性能优化/Unity内存管理/03_Unity内存简介.md
      - 04.Unity Native Memory: 04_性能优化/Unity内存管理/04_Unity_Native_Memory.md
      - 05.Unity Managed Memory: 04_性能优化/Unity内存管理/05_Unity_Managed_Memory.md
  - 实践:
    - Mkdocs:
      - 使用模板: 99_实践/mkdocs/使用模板.md
    - 问题记录:
      - 浮点数运算问题: 99_实践/问题记录/浮点数运算问题.md
      - 记一次语言表的反向优化: 99_实践/问题记录/记一次语言表的反向优化.md

extra:
  homepage: https://peiyuzou.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peiyuzou

markdown_extensions:
  - abbr # 支持缩写和词汇表
  - admonition # 提示块
  - attr_list # 支持注释、网格、按钮、工具提示、带颜色图标、带动画图标、图像对齐、图像延迟加载
  - def_list # 支持定义列表
  - footnotes # 支持脚注（书里面那种123标记，然后页脚分别解释123）
  - md_in_html # 支持html内部编写markdown
  - toc:
      permalink: true
      # toc_depth: 3 # 控制目录最大深度
  - markdown.extensions.tables # 支持数据表
  - pymdownx.arithmatex: # 内联数学公式（对应extra_javascript中的指定配置）
      generic: true
  # - pymdownx.betterem: # 更好地加粗和斜体支持
  #     smart_enable: all
  - pymdownx.blocks.caption: # 支持md块的标题（图片、代码块、表格等、下方和上方显示一个标题文字）
      prepend: false # true代表显示在上方
      auto: true
      auto_level: 0
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark

extra_javascript:
  # 数学公式
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/extra.css